name: test
run-name: ${{ github.actor }}::test deep reinforcement learning repository on linux

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]  # Add more versions as needed

    steps:
    - name: Check out A Deep RL repo
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python modules
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        which python
        which pip

    - name: Run tests
      run: |
        python -m src.envs.env
        pyhton -m src.envs.original_env